on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

name: Update bucket
jobs:
  update:
    name: Update
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Update
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: "1"
